name: Build on MinGW
run-name: building & testing on MinGW
on:
  push:
    branches:
      - 'build-mingw/**'
      - 'build/**'
jobs:
  Build-on-mingw:
    runs-on: windows-latest
    timeout-minutes: 150
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-mpfr
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-graphite2
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-fontconfig
            bison
            texinfo

      - name: make libs
        shell: msys2 {0}
        run: |
          mkdir ./Work
          mkdir ./Work/libs

          mkdir ./Work/libs/zlib
          cd ./Work/libs/zlib
          ../../../libs/zlib/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpng
          cd ./Work/libs/libpng
          ../../../libs/libpng/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpaper
          cd ./Work/libs/libpaper
          ../../../libs/libpaper/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/freetype2
          cd ./Work/libs/freetype2
          ../../../libs/freetype2/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/gd
          cd ./Work/libs/gd
          ../../../libs/gd/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/xpdf
          cd ./Work/libs/xpdf
          ../../../libs/xpdf/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/pplib
          cd ./Work/libs/pplib
          ../../../libs/pplib/configure
          make
          make check || echo -e "**\n** failed: pplib.test\n**"
          cat pplib.log

          cd ../../..
          mkdir ./Work/libs/zziplib
          cd ./Work/libs/zziplib
          ../../../libs/zziplib/configure
          make
          make check || echo -e "**\n** failed: zziplib\n**"

          cd ../../..
          mkdir ./Work/libs/teckit
          cd ./Work/libs/teckit
          ../../../libs/teckit/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/graphite2
          cd ./Work/libs/graphite2
          ../../../libs/graphite2/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/harfbuzz
          cd ./Work/libs/harfbuzz
          ../../../libs/harfbuzz/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/lua53
          cd ./Work/libs/lua53
          ../../../libs/lua53/configure
          make
          make check || echo -e "**\n** failed: lua53\n**"

          cd ../../..
          mkdir ./Work/libs/luajit
          cd ./Work/libs/luajit
          ../../../libs/luajit/configure
          make
          make check || echo -e "**\n** failed: luajit\n**"

          cd ../../..
          mkdir ./Work/libs/potrace
          cd ./Work/libs/potrace
          ../../../libs/potrace/configure
          make
          make check || echo -e "**\n** failed: potrace\n**"

      - name: make texk
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk
          cd ./Work/texk
          for prog in kpathsea ptexenc web2c afm2pl bibtex-x chktex cjkutils detex dtl dvi2tty dvidvi dviljk dviout-util dvipdfm-x dvipng dvipos dvipsk gregorio gsftopk lcdf-typetools makeindexk makejvf mendexk musixtnt ps2pk psutils seetexk tex4htk ttfdump upmendex texlive; do \
            mkdir $prog; \
            cd $prog; \
            ../../../texk/$prog/configure \
              --without-x \
              --with-system-cairo \
              --with-system-gmp \
              --with-system-icu \
                 || echo -e "**\n** failed: configure $prog\n**"; \
            make || echo -e "**\n** failed: make $prog\n**"; \
            make check || echo -e "**\n** failed: make check $prog\n**"; \
            cd ..; \
          done

      - run: echo "⛄ This job's status is ${{ job.status }}."
