name: Build on Ubuntu
run-name: building & testing on Ubuntu
on:
  push:
    branches:
      - 'build-ubuntu/**'
      - 'build/**'
jobs:
  Build-on-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: build
        shell: bash
        run: |
          TL_CONFIGURE="../configure --without-x" ./Build

      - run: echo "⛄ This job's status is ${{ job.status }}."
