name: Build on MinGW
run-name: building & testing on MinGW
on:
  push:
    branches:
      - 'build-mingw/**'
      - 'build/**'
jobs:
  Build-on-mingw:
    runs-on: windows-latest
    timeout-minutes: 150
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-mpfr
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-graphite2
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-fontconfig
            bison
            texinfo

      - name: make libs
        shell: msys2 {0}
        run: |
          mkdir ./Work
          mkdir ./Work/libs

          mkdir ./Work/libs/zlib
          cd ./Work/libs/zlib
          ../../../libs/zlib/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpng
          cd ./Work/libs/libpng
          ../../../libs/libpng/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpaper
          cd ./Work/libs/libpaper
          ../../../libs/libpaper/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/freetype2
          cd ./Work/libs/freetype2
          ../../../libs/freetype2/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/gd
          cd ./Work/libs/gd
          ../../../libs/gd/configure
          make
          make check

      - name: make kpathsea, ptexenc
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk

          mkdir ./Work/texk/kpathsea
          cd ./Work/texk/kpathsea
          ../../../texk/kpathsea/configure
          make
          ## link without libtool
          echo -e "###\n### link without libtool  kpsewhich.exe\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o kpsewhich.exe kpsewhich.o .libs/libkpathsea.a
          make check

          cd ../../..
          mkdir ./Work/texk/ptexenc
          cd ./Work/texk/ptexenc
          ../../../texk/ptexenc/configure
          make

      - name: make libs
        shell: msys2 {0}
        run: |
          mkdir ./Work/libs/xpdf
          cd ./Work/libs/xpdf
          ../../../libs/xpdf/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/pplib
          cd ./Work/libs/pplib
          ../../../libs/pplib/configure
          make
          make check || echo -e "**\n** failed: pplib.test\n**"
          cat pplib.log

          cd ../../..
          mkdir ./Work/libs/zziplib
          cd ./Work/libs/zziplib
          ../../../libs/zziplib/configure
          make
          make check || echo -e "**\n** failed: zziplib\n**"

          cd ../../..
          mkdir ./Work/libs/teckit
          cd ./Work/libs/teckit
          ../../../libs/teckit/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/graphite2
          cd ./Work/libs/graphite2
          ../../../libs/graphite2/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/harfbuzz
          cd ./Work/libs/harfbuzz
          ../../../libs/harfbuzz/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/lua53
          cd ./Work/libs/lua53
          ../../../libs/lua53/configure
          make
          make check || echo -e "**\n** failed: lua53\n**"
          cat luaerror.log

          cd ../../..
          mkdir ./Work/libs/luajit
          cd ./Work/libs/luajit
          ../../../libs/luajit/configure
          make
          make check || echo -e "**\n** failed: luajit\n**"

          cd ../../..
          mkdir ./Work/libs/potrace
          cd ./Work/libs/potrace
          ../../../libs/potrace/configure
          make
          make check || echo -e "**\n** failed: potrace\n**"

      - name: web2c
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/web2c
          cd ./Work/texk/web2c
          ../../../texk/web2c/configure \
            --srcdir=../../../texk/web2c \
            --disable-all-pkgs \
            --enable-debug \
            --enable-tex  --enable-tex-synctex \
            --enable-ptex  --enable-ptex-synctex \
            --enable-eptex  --enable-eptex-synctex \
            --enable-uptex  --enable-uptex-synctex \
            --enable-euptex  --enable-euptex-synctex \
            --enable-mp  --enable-pmp  --enable-upmp \
            --enable-pdftex  --enable-pdftex-synctex \
            --enable-web-progs  --enable-synctex \
            --enable-mf  --enable-mf-nowin \
            --enable-etex  --enable-etex-synctex \
            --enable-aleph \
            --enable-luatex  --enable-luajittex  --enable-luahbtex  --enable-luajithbtex \
            --enable-xetex  --enable-xetex-synctex \
            --enable-mflua  --disable-mflua-nowin  --enable-mfluajit  --disable-mfluajit-nowin \
            --disable-epsfwin  --disable-hp2627win  --disable-mftalkwin  --disable-nextwin \
            --disable-regiswin  --disable-suntoolswin  --disable-tektronixwin  --disable-unitermwin \
            --disable-missing \
            --with-gnu-ld \
            --without-x \
            --without-mf-x-toolkit \
            --without-system-kpathsea \
            --without-system-ptexenc \
            --without-system-zlib \
            --without-system-libpng \
            --without-system-freetype2 \
            --with-system-pixman \
            --with-system-cairo \
            --with-system-gmp \
            --with-system-mpfr \
            --without-system-poppler \
            --without-system-xpdf \
            --without-system-zziplib \
            --without-system-teckit \
            --with-system-icu \
            --without-system-graphite2 \
            --without-system-harfbuzz
          make tangle.exe
          make ctangle.exe
          make ctie.exe
          make ctwill.exe
          make ctwill-refsort.exe
          make ctwill-twinx.exe
          make cweave.exe
          make tie.exe
          make twill.exe

          make tex.p
          make tex.exe
          make etex.web
          make etex.p
          make etex.exe
          make ptex.web
          make ptex.p
          make ptex.exe
          ## link without libtool
          echo -e "###\n### link without libtool  ptex.exe\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o ptex.exe ptexdir/ptex-ptexextra.o ptex-ptexini.o ptex-ptex0.o ptex-ptex-pool.o libkanji.a lib/libp.a /d/a/texlive-source/texlive-source/Work/texk/ptexenc/.libs/libptexenc.a lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a -lwsock32 || echo -e "**\n** fail to link ptex.exe"

          make uptex.web
          make uptex.p
          make uptex.exe
          ## link without libtool
          echo -e "###\n### link without libtool  uptex.exe\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o uptex.exe uptexdir/uptex-uptexextra.o uptex-uptexini.o uptex-uptex0.o uptex-uptex-pool.o libukanji.a lib/libp.a /d/a/texlive-source/texlive-source/Work/texk/ptexenc/.libs/libptexenc.a lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a -lwsock32 || echo -e "**\n** fail to link uptex.exe"

          make eptex.web
          make eptex.p
          make eptex.exe
          ## link without libtool
          echo -e "###\n### link without libtool  eptex.exe\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o eptex.exe eptexdir/eptex-eptexextra.o synctexdir/eptex-synctex.o eptex-eptexini.o eptex-eptex0.o eptex-eptex-pool.o libkanji.a lib/libp.a /d/a/texlive-source/texlive-source/Work/texk/ptexenc/.libs/libptexenc.a lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a -lwsock32 libmd5.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a || echo -e "**\n** fail to link eptex.exe"

          make euptex.web
          make euptex.p
          make euptex.exe
          ## link without libtool
          echo -e "###\n### link without libtool  euptex.exe\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o euptex.exe euptexdir/euptex-euptexextra.o synctexdir/euptex-synctex.o euptex-euptexini.o euptex-euptex0.o euptex-euptex-pool.o libukanji.a lib/libp.a /d/a/texlive-source/texlive-source/Work/texk/ptexenc/.libs/libptexenc.a lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a -lwsock32 libmd5.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a || echo -e "**\n** fail to link euptex.exe"

          make dvitype.exe
          make dvicopy.exe
          make pltotf.exe
          make tftopl.exe
          make bibtex.exe
          make gftodvi.exe
          make gftopk.exe
          make gftype.exe
          make mft.exe
          make patgen.exe
          make pktogf.exe
          make pktype.exe
          make pooltype.exe
          make vftovp.exe
          make vptovf.exe
          make weave.exe

          make pdftex.exe || echo "fail to make pdftex.exe"
          ## link without libtool
          echo -e "###\n### link without libtool  pdftex.exe\n###"
          g++ -Wreturn-type -Wno-write-strings -g -O2   -o pdftex.exe pdftexdir/pdftex-pdftexextra.o synctexdir/pdftex-synctex.o pdftex-pdftexini.o pdftex-pdftex0.o pdftex-pdftex-pool.o libpdftex.a /d/a/texlive-source/texlive-source/Work/libs/libpng/libpng.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a /d/a/texlive-source/texlive-source/Work/libs/xpdf/libxpdf.a -lgdi32 libmd5.a lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a -lwsock32 || echo -e "**\n** fail to link pdftex.exe"

          make mf.exe || echo "fail to make mf.exe"

          make xetex.exe || echo "fail to make xetex.exe"
          ## link without libtool
          echo -e "###\n### link without libtool  xetex.exe\n###"
          g++  -g -O2   -o xetex.exe xetexdir/xetex-xetexextra.o synctexdir/xetex-synctex.o xetex-xetexini.o xetex-xetex0.o xetex-xetex-pool.o libxetex.a /d/a/texlive-source/texlive-source/Work/libs/harfbuzz/libharfbuzz.a /d/a/texlive-source/texlive-source/Work/libs/graphite2/libgraphite2.a -L/mingw64/lib -licuin -licuuc -licudt -lpthread -lm     /d/a/texlive-source/texlive-source/Work/libs/teckit/libTECkit.a /d/a/texlive-source/texlive-source/Work/libs/libpng/libpng.a /d/a/texlive-source/texlive-source/Work/libs/freetype2/libfreetype.a /d/a/texlive-source/texlive-source/Work/libs/pplib/libpplib.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a libmd5.a -lfontconfig -lfreetype lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a -lwsock32 || echo -e "**\n** fail to link xetex.exe"

          make pmpost.exe || echo "fail to make pmpost.exe"
          make upmpost.exe || echo "fail to make upmpost.exe"

          echo "!!! make complete !!!"

      - name: web2c version check
        shell: msys2 {0}
        run: |
          cd ./Work/texk/web2c
          ls -l ./*.exe
        env:
          TEXMFCNF: "../../../texk/kpathsea"

      - name: web2c triptest
        shell: msys2 {0}
        run: |
          cd ./Work/texk/web2c

          export abs_srcdir=../$srcdir
          export LN_S=cp
          export DIFF=diff
          export DIFFFLAGS="--strip-trailing-cr --ignore-matching-lines 'DVItype'"
          ./pltotf --version || echo
          ./tftopl --version || echo
          ./dvitype --version || echo
          ./gftype --version || echo
          $srcdir/mftraptest.test            || { echo -e "**\n** failed: mftraptest.test\n**"            ; cat mftraptest.log ; }
          $srcdir/triptest.test              || { echo -e "**\n** failed: triptest.test\n**"              ; cat triptest.log ; }
          $srcdir/etexdir/etriptest.test     || { echo -e "**\n** failed: etexdir/etriptest.test\n**"     ; cat etriptest.log ; }
          $srcdir/eptexdir/pdfprimitive.test || { echo -e "**\n** failed: eptexdir/pdfprimitive.test\n**" ; cat pdfprimitivetest.log ; }
          $srcdir/ptexdir/ptriptest.test     || { echo -e "**\n** failed: ptexdir/ptriptest.test\n**"     ; cat ptexdir/ptriptest.log ; }
          $srcdir/uptexdir/ptriptest.test    || { echo -e "**\n** failed: uptexdir/ptriptest.test\n**"    ; cat uptexdir/ptriptest.log ; }
          $srcdir/uptexdir/uptriptest.test   || { echo -e "**\n** failed: uptexdir/uptriptest.test\n**"   ; cat uptexdir/uptriptest.log ; }
          $srcdir/eptexdir/eptriptest.test   || { echo -e "**\n** failed: eptexdir/eptriptest.test\n**"   ; cat eptexdir/eptriptest.log ; }
          $srcdir/euptexdir/euptriptest.test || { echo -e "**\n** failed: euptexdir/euptriptest.test\n**" ; cat euptexdir/euptriptest.log ; }
        env:
          srcdir: "../../../texk/web2c"
          TEXMFCNF: "../../../texk/kpathsea"

      - name: web2c check pTeX
        shell: msys2 {0}
        run: |
          cd ./Work/texk/web2c
          chcp.com
          $srcdir/ptexdir/wcfname.test          || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
          $srcdir/eptexdir/wcfname.test         || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
          $srcdir/uptexdir/wcfname0.test        || echo -e "**\n** failed: uptexdir/wcfname0.test\n**"
          $srcdir/euptexdir/wcfname0.test       || echo -e "**\n** failed: euptexdir/wcfname0.test\n**"
          chcp.com 932
          $srcdir/ptexdir/wcfname.test          || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
          $srcdir/eptexdir/wcfname.test         || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
          $srcdir/uptexdir/wcfname0.test        || echo -e "**\n** failed: uptexdir/wcfname0.test\n**"
          $srcdir/euptexdir/wcfname0.test       || echo -e "**\n** failed: euptexdir/wcfname0.test\n**"
          locale -a
        env:
          srcdir: "../../../texk/web2c"
          TEXMFCNF: "../../../texk/kpathsea"
          guess_input_kanji_encoding: "1"
          command_line_encoding: "none"
          ExeExt: ".exe"

      - name: web2c check upTeX
        shell: msys2 {0}
        run: |
          cd ./Work/texk/web2c
          chcp.com
          $srcdir/uptexdir/wcfname.test         || echo -e "**\n** failed: uptexdir/wcfname.test\n**"
          $srcdir/euptexdir/wcfname.test        || echo -e "**\n** failed: euptexdir/wcfname.test\n**"
          $srcdir/pdftexdir/wcfname.test        || echo -e "**\n** failed: pdftexdir/wcfname.test\n**"
          $srcdir/xetexdir/wcfname.test         || echo -e "**\n** failed: xetexdir/wcfname.test\n**"
        env:
          srcdir: "../../../texk/web2c"
          TEXMFCNF: "../../../texk/kpathsea"
          command_line_encoding: "utf-8"

      - name: web2c, make, make check
        shell: msys2 {0}
        run: |
          cd ./Work/texk/web2c
          make       || echo "**\n** failed: web2c: make\n**"
          make check || echo "**\n** failed: web2c: make check\n**"

      #- name: ttf2pk2
      #  shell: msys2 {0}
      #  run: |
      #    prog='ttf2pk2'
      #    mkdir -p ./Work/texk/$prog
      #    cd ./Work/texk/$prog
      #    ../../../texk/$prog/configure
      #    make
      #    make check || echo -e "**\n** failed: ttf2pk2\n**"
      #    cat tests/ttf2pk.log || echo

      - run: echo "⛄ This job's status is ${{ job.status }}."
