name: Build on Ubuntu
run-name: building & testing on Ubuntu
on:
  push:
    branches:
      - 'build-ubuntu/**'
      - 'build/**'
jobs:
  Build-on-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: make libs
        shell: bash
        run: |
          mkdir -p ./Work/libs/{zlib,libpng,libpaper,freetype2,gd,potrace}
          cd ${{ github.workspace }}/Work/libs/zlib
          ../../../libs/zlib/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/libpng
          ../../../libs/libpng/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/libpaper
          ../../../libs/libpaper/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/freetype2
          ../../../libs/freetype2/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/gd
          ../../../libs/gd/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/potrace
          ../../../libs/potrace/configure
          make
          make check

      - name: make kpathsea, ptexenc
        shell: bash
        run: |
          mkdir -p ./Work/texk/{kpathsea,ptexenc}
          cd ${{ github.workspace }}/Work/texk/kpathsea
          ../../../texk/kpathsea/configure
          make
          make check
          cd ${{ github.workspace }}/Work/texk/ptexenc
          ../../../texk/ptexenc/configure
          make

      - name: make libs
        shell: bash
        run: |
          mkdir -p ./Work/libs/{gmp,mpfr,xpdf,pplib}
          cd ${{ github.workspace }}/Work/libs/gmp
          ../../../libs/gmp/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/mpfr
          ../../../libs/mpfr/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/xpdf
          ../../../libs/xpdf/configure
          make
          make check
          cd ${{ github.workspace }}/Work/libs/pplib
          ../../../libs/pplib/configure
          make
          make check

      - name: web2c
        shell: bash
        run: |
          mkdir -p ./Work/texk/web2c
          cd ./Work/texk/web2c
          ../../../texk/web2c/configure \
            --srcdir=../../../texk/web2c \
            --disable-all-pkgs \
            --enable-debug \
            --disable-tex  --disable-tex-synctex \
            --enable-ptex  --enable-ptex-synctex \
            --enable-eptex  --enable-eptex-synctex \
            --enable-uptex  --enable-uptex-synctex \
            --enable-euptex  --enable-euptex-synctex \
            --disable-mp  --enable-pmp  --enable-upmp \
            --enable-pdftex  --enable-pdftex-synctex \
            --enable-web-progs  --enable-synctex \
            --disable-mf  --disable-mf-nowin \
            --disable-etex  --disable-etex-synctex \
            --disable-aleph \
            --disable-luatex  --disable-luajittex  --disable-luahbtex  --disable-luajithbtex \
            --enable-xetex  --enable-xetex-synctex \
            --disable-mflua  --disable-mflua-nowin  --disable-mfluajit  --disable-mfluajit-nowin \
            --disable-epsfwin  --disable-hp2627win  --disable-mftalkwin  --disable-nextwin \
            --disable-regiswin  --disable-suntoolswin  --disable-tektronixwin  --disable-unitermwin \
            --disable-missing \
            --with-gnu-ld \
            --without-x \
            --without-mf-x-toolkit \
            --without-system-kpathsea \
            --without-system-ptexenc \
            --without-system-zlib \
            --without-system-libpng \
            --without-system-freetype2 \
            --with-system-pixman \
            --with-system-cairo \
            --without-system-gmp \
            --without-system-mpfr \
            --without-system-poppler \
            --without-system-xpdf \
            --with-system-zziplib \
            --with-system-teckit \
            --with-system-icu \
            --with-system-graphite2 \
            --with-system-harfbuzz
          make
          make check

      - run: echo "⛄ This job's status is ${{ job.status }}."
