name: Build on MinGW
run-name: building & testing on MinGW
on:
  push:
    branches:
      - 'build-mingw/**'
      - 'build/**'
jobs:
  Build-on-mingw:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-mpfr
            bison
            texinfo

      - name: make libs
        shell: msys2 {0}
        run: |
          mkdir ./Work
          mkdir ./Work/libs

          mkdir ./Work/libs/zlib
          cd ./Work/libs/zlib
          ../../../libs/zlib/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpng
          cd ./Work/libs/libpng
          ../../../libs/libpng/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/libpaper
          cd ./Work/libs/libpaper
          ../../../libs/libpaper/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/freetype2
          cd ./Work/libs/freetype2
          ../../../libs/freetype2/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/gd
          cd ./Work/libs/gd
          ../../../libs/gd/configure
          make
          make check

          cd ../../..
          mkdir ./Work/libs/potrace
          cd ./Work/libs/potrace
          ../../../libs/potrace/configure
          make
          make check || echo -e "**\n** failed: potrace\n**"

      - name: make kpathsea, ptexenc
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk

          mkdir ./Work/texk/kpathsea
          cd ./Work/texk/kpathsea
          ../../../texk/kpathsea/configure
          make
          make check

          cd ../../..
          mkdir ./Work/texk/ptexenc
          cd ./Work/texk/ptexenc
          ../../../texk/ptexenc/configure
          make

      - name: dvisvgm
        shell: msys2 {0}
        run: |
          prog='dvisvgm'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check

      - name: chktex
        shell: msys2 {0}
        run: |
          prog='chktex'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: chktex\n**"

      - name: cjkutils
        shell: msys2 {0}
        run: |
          prog='cjkutils'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: cjkutils\n**"

      - name: detex
        shell: msys2 {0}
        run: |
          prog='detex'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: detex\n**"

      - name: dtl
        shell: msys2 {0}
        run: |
          prog='dtl'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: dtl\n**"
          cat dtl.log || echo

      - name: dviljk
        shell: msys2 {0}
        run: |
          prog='dviljk'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: dviljk\n**"

      - name: dvipng
        shell: msys2 {0}
        run: |
          prog='dvipng'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: dvipng\n**"

      - name: dvipos
        shell: msys2 {0}
        run: |
          prog='dvipos'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: dvipos\n**"

      - name: gregorio
        shell: msys2 {0}
        run: |
          prog='gregorio'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: gregorio\n**"

      - name: gsftopk
        shell: msys2 {0}
        run: |
          prog='gsftopk'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: gsftopk\n**"

      - name: lcdf-typetools
        shell: msys2 {0}
        run: |
          prog='lcdf-typetools'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: lcdf-typetools\n**"
          cat tests/tfm.log || echo

      - name: makeindex
        shell: msys2 {0}
        run: |
          prog='makeindexk'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: makeindex\n**"

      - name: musixtnt
        shell: msys2 {0}
        run: |
          prog='musixtnt'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: musixtnt\n**"

      - name: ps2pk
        shell: msys2 {0}
        run: |
          prog='ps2pk'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: ps2pk\n**"

      - name: psutils
        shell: msys2 {0}
        run: |
          prog='psutils'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: psutils\n**"
          cat psutils.log || echo

      - name: tex4htk
        shell: msys2 {0}
        run: |
          prog='tex4htk'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: tex4ht\n**"

      - name: texlive
        shell: msys2 {0}
        run: |
          prog='texlive'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: texlive\n**"

      - name: ttfdump
        shell: msys2 {0}
        run: |
          prog='ttfdump'
          mkdir -p ./Work/texk/$prog
          cd ./Work/texk/$prog
          ../../../texk/$prog/configure
          make
          make check || echo -e "**\n** failed: ttfdump\n**"

      - name: upmendex
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/upmendex
          cd ./Work/texk/upmendex
          ../../../texk/upmendex/configure \
            --with-system-icu
          make
          ./upmendex --help
          make check

      - name: dvipdfm-x
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/dvipdfm-x
          cd ./Work/texk/dvipdfm-x
          ../../../texk/dvipdfm-x/configure
          make
          make check

      - name: dvipsk
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/dvipsk
          cd ./Work/texk/dvipsk
          ../../../texk/dvipsk/configure
          make
          make check

      - name: makejvf
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/makejvf
          cd ./Work/texk/makejvf
          ../../../texk/makejvf/configure
          make
          make check

      - name: mendex
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/mendexk
          cd ./Work/texk/mendexk
          ../../../texk/mendexk/configure
          make
          make check

      - name: dviout-util
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/dviout-util
          cd ./Work/texk/dviout-util
          ../../../texk/dviout-util/configure
          make
          make check

      - name: dvi2tty
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/dvi2tty
          cd ./Work/texk/dvi2tty
          ../../../texk/dvi2tty/configure
          make
          make check

      - name: seetex
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/seetexk
          cd ./Work/texk/seetexk
          ../../../texk/seetexk/configure
          make
          export ExeExt=.exe
          make check

      - name: dvidvi
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/dvidvi
          cd ./Work/texk/dvidvi
          ../../../texk/dvidvi/configure
          make
          make check
        env:
          TEXMFCNF: "../../../texk/kpathsea"

      - name: bibtex-x
        shell: msys2 {0}
        run: |
          mkdir ./Work/texk/bibtex-x
          cd ./Work/texk/bibtex-x
          ../../../texk/bibtex-x/configure \
            --with-system-icu
          make
          ## link without libtool
          echo -e "###\n### link without libtool\n###"
          gcc -Wimplicit -Wreturn-type -g -O2   -o bibtex8.exe bibtex8-bibtex-1.o bibtex8-bibtex-2.o bibtex8-bibtex-3.o bibtex8-bibtex-4.o bibtex8-bibtex.o bibtex8-utils.o ../../texk/kpathsea/.libs/libkpathsea.a
          g++  -g -O2   -o bibtexu.exe bibtexu-bibtex-1.o bibtexu-bibtex-2.o bibtexu-bibtex-3.o bibtexu-bibtex-4.o bibtexu-bibtex.o bibtexu-utils.o ../../texk/kpathsea/.libs/libkpathsea.a -L/mingw64/lib  -licuio -licuin -licuuc -licudt -lpthread -lm
          ./bibtex8.exe --version
          ./bibtexu.exe --version
          make check
        env:
          ExeExt: ".exe"
          TEXMFCNF: "../../../texk/kpathsea"

      - run: echo "⛄ This job's status is ${{ job.status }}."
